version: '3.9'

services:
  db:
    image: mysql:5.7
    container_name: golden-events-db
    environment:
      MYSQL_DATABASE: 'golden-events'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3308:3306"
    volumes:
      - mysql-db:/var/lib/mysql

  api:
    container_name: golden-events-api
    build: 
      context: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"

  web:
    container_name: golden-events-web
    build:
      context: ./frontend
    depends_on:
      - api
      - db
    ports:
      - "3000:3000" 

volumes:
  mysql-db: